### ISSUE TITLE
Bug with symbols

### ISSUE THREAD

**Issue by Toper9636** [mdisprgm/bdsx-anticrasher#1]
Symbol not found: ?disconnect@NetworkConnection@@QEAAXXZ
   at Anonymous function (C:\bdsx\plugins\AntiCheat\src\AntiPacket.ts:12:1)
Symbol not found: ?receivePacket@NetworkConnection@@QEAA?AW4DataStatus@NetworkPeer@@AEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAVNetworkSystem@@AEBV?$shared_ptr@V?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@chrono@std@@@5@@Z
   at Anonymous function (C:\bdsx\plugins\AntiCheat\src\AntiPacket.ts:14:1)

**Comment by Toper9636** [comment]
Symbol not found: ?disconnect@NetworkConnection@@QEAAXXZ
   at Anonymous function (C:\bdsx\plugins\AntiCheat\src\AntiPacket.ts:12:1)
